module Locales.Components.Mockups where

import Locales.Prelude

data DashboardLocale = DashboardLocale
    { navTitle :: Text
    , graphTitle :: Text
    , insightsTitle :: Text
    , stats :: [DashboardStat]
    , insights :: [DashboardInsight]
    }

data DashboardStat = DashboardStat
    { label :: Text
    , value :: Text
    }

data DashboardInsight = DashboardInsight
    { agent :: Text
    , message :: Text
    , priority :: Text
    }

dashboardLocale :: Language -> DashboardLocale
dashboardLocale EN = DashboardLocale
    { navTitle = "Ruzaani — Dashboard"
    , graphTitle = "Performance Trend"
    , insightsTitle = "AI Insights"
    , stats = 
        [ DashboardStat { label = "Sales", value = "1,284" }
        , DashboardStat { label = "Revenue", value = "$42.8K" }
        , DashboardStat { label = "ROI", value = "4.8x" }
        ]
    , insights = 
        [ DashboardInsight { agent = "Strategist", message = "ROAS exceeded 4.0 on Meta Ads campaign", priority = "high" }
        , DashboardInsight { agent = "Analyst", message = "High-value account detected from organic search", priority = "medium" }
        , DashboardInsight { agent = "Sentinel", message = "Positive sentiment trend in Instagram comments", priority = "low" }
        ]
    }
dashboardLocale ES = DashboardLocale
    { navTitle = "Ruzaani — Dashboard"
    , graphTitle = "Tendencia de Rendimiento"
    , insightsTitle = "Insights de IA"
    , stats = 
        [ DashboardStat { label = "Ventas", value = "1,284" }
        , DashboardStat { label = "Ingresos", value = "$42.8K" }
        , DashboardStat { label = "ROI", value = "4.8x" }
    ]
    , insights = 
        [ DashboardInsight { agent = "Strategist", message = "ROAS superó 4.0 en campaña de Meta Ads", priority = "high" }
        , DashboardInsight { agent = "Analyst", message = "Cuenta de alto valor detectada desde sitio web", priority = "medium" }
        , DashboardInsight { agent = "Sentinel", message = "Tendencia de sentimiento positivo en Instagram", priority = "low" }
        ]
    }
dashboardLocale KO = DashboardLocale
    { navTitle = "Ruzaani — 대시보드"
    , graphTitle = "성과 트렌드"
    , insightsTitle = "AI 인사이트"
    , stats = 
        [ DashboardStat { label = "총 판매량", value = "1,284" }
        , DashboardStat { label = "매출", value = "$42.8K" }
        , DashboardStat { label = "ROI", value = "4.8x" }
        ]
    , insights = 
        [ DashboardInsight { agent = "Strategist", message = "Meta Ads 캠페인 ROAS가 4.0을 초과했습니다", priority = "high" }
        , DashboardInsight { agent = "Analyst", message = "유기적 검색에서 고가치 계정이 감지되었습니다", priority = "medium" }
        , DashboardInsight { agent = "Sentinel", message = "Instagram 댓글에서 긍정적인 감정 트렌드 감지", priority = "low" }
        ]
    }

data AgencyLocale = AgencyLocale
    { navTitle :: Text
    , activeClient :: Text
    , clientLabel :: Text
    , clients :: [AgencyClient]
    , reportTitle :: Text
    , reportBrand :: Text
    }

data AgencyClient = AgencyClient
    { name :: Text
    , status :: Text
    , agent :: Text
    }

agencyLocale :: Language -> AgencyLocale
agencyLocale EN = AgencyLocale
    { navTitle = "Agency Control Center"
    , activeClient = "Switch Workspace"
    , clientLabel = "Clients"
    , clients = 
        [ AgencyClient { name = "Eco-Grow Solutions", status = "Active", agent = "SDR + Closer" }
        , AgencyClient { name = "Urban Real Estate", status = "Active", agent = "Analyst Only" }
        , AgencyClient { name = "Nexus SaaS", status = "Paused", agent = "All Agents" }
        ]
    , reportTitle = "White-Label Report Preview"
    , reportBrand = "Generated by [Your Agency Name]"
    }
agencyLocale ES = AgencyLocale
    { navTitle = "Centro de Control de Agencia"
    , activeClient = "Cambiar Espacio de Trabajo"
    , clientLabel = "Clientes"
    , clients = 
        [ AgencyClient { name = "Soluciones Eco-Grow", status = "Activo", agent = "SDR + Closer" }
        , AgencyClient { name = "Inmobiliaria Urbana", status = "Activo", agent = "Solo Analyst" }
        , AgencyClient { name = "Nexus SaaS", status = "Pausado", agent = "Todos los Agentes" }
        ]
    , reportTitle = "Vista Previa de Informe Marca Blanca"
    , reportBrand = "Generado por [Tu Agencia]"
    }
agencyLocale KO = AgencyLocale
    { navTitle = "Ruzaani — 에이전시"
    , activeClient = "워크스페이스 전환"
    , clientLabel = "클라이언트"
    , clients = 
        [ AgencyClient { name = "에코-그로우 솔루션", status = "활성", agent = "SDR + Closer" }
        , AgencyClient { name = "어반 리얼 에스테이트", status = "활성", agent = "Analyst 전용" }
        , AgencyClient { name = "넥서스 SaaS", status = "일시중지", agent = "전체 에이전트" }
        ]
    , reportTitle = "화이트라벨 리포트 미리보기"
    , reportBrand = "생성자: [에이전시 이름]"
    }
