module Locales.Components.Mockups where

import Locales.Prelude

data DashboardLocale = DashboardLocale
    { navTitle :: Text
    , graphTitle :: Text
    , insightsTitle :: Text
    , stats :: [DashboardStat]
    , insights :: [DashboardInsight]
    }

data DashboardStat = DashboardStat
    { label :: Text
    , value :: Text
    }

data DashboardInsight = DashboardInsight
    { agent :: Text
    , message :: Text
    , priority :: Text
    }

dashboardLocale :: Language -> DashboardLocale
dashboardLocale EN = DashboardLocale
    { navTitle = "Ruzaani — Dashboard"
    , graphTitle = "Performance Trend"
    , insightsTitle = "AI Insights"
    , stats = 
        [ DashboardStat { label = "Sales", value = "1,284" }
        , DashboardStat { label = "Revenue", value = "$42.8K" }
        , DashboardStat { label = "ROI", value = "4.8x" }
        ]
    , insights = 
        [ DashboardInsight { agent = "Strategist", message = "ROAS exceeded 4.0 on Meta Ads campaign", priority = "high" }
        , DashboardInsight { agent = "Analyst", message = "High-value account detected from organic search", priority = "medium" }
        , DashboardInsight { agent = "Sentinel", message = "Positive sentiment trend in Instagram comments", priority = "low" }
        ]
    }
dashboardLocale ES = DashboardLocale
    { navTitle = "Ruzaani — Dashboard"
    , graphTitle = "Tendencia de Rendimiento"
    , insightsTitle = "Insights de IA"
    , stats = 
        [ DashboardStat { label = "Ventas", value = "1,284" }
        , DashboardStat { label = "Ingresos", value = "$42.8K" }
        , DashboardStat { label = "ROI", value = "4.8x" }
    ]
    , insights = 
        [ DashboardInsight { agent = "Strategist", message = "ROAS superó 4.0 en campaña de Meta Ads", priority = "high" }
        , DashboardInsight { agent = "Analyst", message = "Cuenta de alto valor detectada desde sitio web", priority = "medium" }
        , DashboardInsight { agent = "Sentinel", message = "Tendencia de sentimiento positivo en Instagram", priority = "low" }
        ]
    }
dashboardLocale KO = DashboardLocale
    { navTitle = "Ruzaani — 대시보드"
    , graphTitle = "성과 트렌드"
    , insightsTitle = "AI 인사이트"
    , stats = 
        [ DashboardStat { label = "총 판매량", value = "1,284" }
        , DashboardStat { label = "매출", value = "$42.8K" }
        , DashboardStat { label = "ROI", value = "4.8x" }
        ]
    , insights = 
        [ DashboardInsight { agent = "Strategist", message = "Meta Ads 캠페인 ROAS가 4.0을 초과했습니다", priority = "high" }
        , DashboardInsight { agent = "Analyst", message = "유기적 검색에서 고가치 계정이 감지되었습니다", priority = "medium" }
        , DashboardInsight { agent = "Sentinel", message = "Instagram 댓글에서 긍정적인 감정 트렌드 감지", priority = "low" }
        ]
    }

data AgencyLocale = AgencyLocale
    { navTitle :: Text
    , activeClient :: Text
    , clientLabel :: Text
    , clients :: [AgencyClient]
    , reportTitle :: Text
    , reportBrand :: Text
    }

data AgencyClient = AgencyClient
    { name :: Text
    , status :: Text
    , agent :: Text
    }

agencyLocale :: Language -> AgencyLocale
agencyLocale EN = AgencyLocale
    { navTitle = "Agency Control Center"
    , activeClient = "Switch Workspace"
    , clientLabel = "Clients"
    , clients = 
        [ AgencyClient { name = "Eco-Grow Solutions", status = "Active", agent = "SDR + Closer" }
        , AgencyClient { name = "Urban Real Estate", status = "Active", agent = "Analyst Only" }
        , AgencyClient { name = "Nexus SaaS", status = "Paused", agent = "All Agents" }
        ]
    , reportTitle = "White-Label Report Preview"
    , reportBrand = "Generated by [Your Agency Name]"
    }
agencyLocale ES = AgencyLocale
    { navTitle = "Centro de Control de Agencia"
    , activeClient = "Cambiar Espacio de Trabajo"
    , clientLabel = "Clientes"
    , clients = 
        [ AgencyClient { name = "Soluciones Eco-Grow", status = "Activo", agent = "SDR + Closer" }
        , AgencyClient { name = "Inmobiliaria Urbana", status = "Activo", agent = "Solo Analyst" }
        , AgencyClient { name = "Nexus SaaS", status = "Pausado", agent = "Todos los Agentes" }
        ]
    , reportTitle = "Vista Previa de Informe Marca Blanca"
    , reportBrand = "Generado por [Tu Agencia]"
    }
agencyLocale KO = AgencyLocale
    { navTitle = "Ruzaani — 에이전시"
    , activeClient = "워크스페이스 전환"
    , clientLabel = "클라이언트"
    , clients = 
        [ AgencyClient { name = "에코-그로우 솔루션", status = "활성", agent = "SDR + Closer" }
        , AgencyClient { name = "어반 리얼 에스테이트", status = "활성", agent = "Analyst 전용" }
        , AgencyClient { name = "넥서스 SaaS", status = "일시중지", agent = "전체 에이전트" }
        ]
    , reportTitle = "화이트라벨 리포트 미리보기"
    , reportBrand = "생성자: [에이전시 이름]"
    }


data ConversationLocale = ConversationLocale
    { agent :: Text
    , live :: Text
    , messages :: [ConversationMessage]
    , response :: Text
    , score :: Text
    }

data ConversationMessage = ConversationMessage
    { direction :: Text
    , sender :: Text
    , message :: Html
    }

conversationLocale :: Language -> ConversationLocale
conversationLocale EN = ConversationLocale
    { agent = "SDR Agent"
    , live = "Live"
    , messages = 
        [ ConversationMessage { direction = "receive", sender = "Lead", message = "Hi, how fast can you set up the AI for our agency?" } 
        , ConversationMessage { direction = "send", sender = "SDR Agent", message = "Less than a week. How many clients are you managing right now?" } 
        , ConversationMessage { direction = "receive", sender = "Lead", message = "About 12. We've been burning time on custom automation builds." } 
        , ConversationMessage { direction = "send", sender = "SDR Agent", message = "Ok. Let me show you our dashboard for agencies: <span class=\"fw-semibold\">book a 20-min call ↗</span>" } 
        ]
    , response = "Response: 38s"
    , score = "Score: 87"
    }
conversationLocale ES = ConversationLocale
    { agent = "SDR Agent"
    , live = "Live"
    , messages = 
        [ ConversationMessage { direction = "receive", sender = "Lead", message = "Hi, how fast can you set up the AI for our agency?" } 
        , ConversationMessage { direction = "send", sender = "SDR Agent", message = "Less than a week. How many clients are you managing right now?" } 
        , ConversationMessage { direction = "receive", sender = "Lead", message = "About 12. We've been burning time on custom automation builds." } 
        , ConversationMessage { direction = "send", sender = "SDR Agent", message = "Ok. Let me show you our dashboard for agencies: <span class=\"fw-semibold\">book a 20-min call ↗</span>" } 
        ]
    , response = "Response: 38s"
    , score = "Score: 87"
    }
conversationLocale KO = ConversationLocale
    { agent = "SDR Agent"
    , live = "Live"
    , messages = 
        [ ConversationMessage { direction = "receive", sender = "Lead", message = "Hi, how fast can you set up the AI for our agency?" } 
        , ConversationMessage { direction = "send", sender = "SDR Agent", message = "Less than a week. How many clients are you managing right now?" } 
        , ConversationMessage { direction = "receive", sender = "Lead", message = "About 12. We've been burning time on custom automation builds." } 
        , ConversationMessage { direction = "send", sender = "SDR Agent", message = "Ok. Let me show you our dashboard for agencies: <span class=\"fw-semibold\">book a 20-min call ↗</span>" } 
        ]
    , response = "Response: 38s"
    , score = "Score: 87"
    }


data ProductMockupLocale = ProductMockupLocale
    { title :: Text
    , stats :: [DashboardStat]
    , graphTitle :: Text
    , graphLast :: Text
    , graphLabels :: [Text]
    , listTitle :: Text
    , listData :: [ProductMockupList]
    }

data ProductMockupList = ProductMockupList
    { icon :: Text
    , color :: Text
    , name :: Text
    , msg :: Text
    , score :: Text
    }

productMockupLocale :: Language -> ProductMockupLocale
productMockupLocale EN = ProductMockupLocale
    { title = "Ruzaani — Live Intelligence View"
    , stats = 
        [ DashboardStat { label = "Active Leads", value = "28" }
        , DashboardStat { label = "Resp. Rate", value = "94%" }
        , DashboardStat { label = "ROAS", value = "4.1x" }
        ]
    , graphTitle = "Deal Pipeline"
    , graphLast = "$42K pipeline"
    , graphLabels = ["Qualified", "Proposal", "Won"]
    , listTitle = "Live Conversations"
    , listData = 
        [ ProductMockupList { icon = "fa-brands fa-whatsapp", color = "#25D366", name = "Sarah J.", msg = "SDR → qualifying budget", score = "87" }
        , ProductMockupList { icon = "fa-brands fa-instagram", color = "#E1306C", name = "Michael K.", msg = "Closer → handling objection", score = "142" }
        , ProductMockupList { icon = "fa-solid fa-envelope", color = "#0AAD95", name = "Emily W.", msg = "Closer → booking confirmed", score = "210" }
        ]
    }
productMockupLocale ES = ProductMockupLocale
    { title = "Ruzaani — Vista de Inteligencia en Vivo"
    , stats = 
        [ DashboardStat { label = "Leads Activos", value = "28" }
        , DashboardStat { label = "Tasa Resp.", value = "94%" }
        , DashboardStat { label = "ROAS", value = "4.1x" }
        ]
    , graphTitle = "Pipeline de Tratos"
    , graphLast = "$42K en pipeline"
    , graphLabels = ["Calificado", "Propuesta", "Ganado"]
    , listTitle = "Conversaciones en Vivo"
    , listData = 
        [ ProductMockupList { icon = "fa-brands fa-whatsapp", color = "#25D366", name = "Valentina R.", msg = "SDR → calificando presupuesto", score = "87" }
        , ProductMockupList { icon = "fa-brands fa-instagram", color = "#E1306C", name = "Carlos M.", msg = "Closer → manejando objeción", score = "142" }
        , ProductMockupList { icon = "fa-solid fa-envelope", color = "#0AAD95", name = "Sofia L.", msg = "Closer → reserva confirmada", score = "210" }
        ]
    }
productMockupLocale KO = ProductMockupLocale
    { title = "Ruzaani — 실시간 인텔리전스 뷰"
    , stats = 
        [ DashboardStat { label = "활성 리드", value = "28" }
        , DashboardStat { label = "응답률", value = "94%" }
        , DashboardStat { label = "ROAS", value = "4.1x" }
        ]
    , graphTitle = "딜 파이프라인"
    , graphLast = "$42K 파이프라인"
    , graphLabels = ["검증됨", "제안됨", "성공"]
    , listTitle = "실시간 대화"
    , listData = 
        [ ProductMockupList { icon = "fa-brands fa-whatsapp", color = "#25D366", name = "김지원", msg = "SDR → 예산 검증 중", score = "87" }
        , ProductMockupList { icon = "fa-brands fa-instagram", color = "#E1306C", name = "박상훈", msg = "Closer → 이의 제기 처리 중", score = "142" }
        , ProductMockupList { icon = "fa-solid fa-envelope", color = "#0AAD95", name = "이서연", msg = "Closer → 예약 확정됨", score = "210" }
        ]
    }
